#!/usr/bin/env bash
# Shared defaults for the pipeline scripts. Every value can be overridden from the environment,
# which is how a CI system (GitHub Actions, GitLab CI, Azure DevOps, Jenkins, ...) parameterizes them.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
APP_DIR="${APP_DIR:-$REPO_ROOT/sample/my-agent}"          # directory containing langgraph.json
DOCKERFILE="${DOCKERFILE:-$REPO_ROOT/sample/Dockerfile}"  # generated by `langgraph dockerfile`

IMAGE_REPO="${IMAGE_REPO:-my-agent}"                      # repository name without registry
if [ -z "${IMAGE_TAG:-}" ]; then
  # Immutable tag: short git sha when inside a git repo, otherwise "dev".
  IMAGE_TAG="$(git -C "$APP_DIR" rev-parse --short HEAD 2>/dev/null || echo dev)"
fi
REGISTRY="${REGISTRY:-}"                                  # e.g. registry.example.internal/platform
KIND_CLUSTER="${KIND_CLUSTER:-}"                          # set to side-load the image into kind instead of pushing
PLATFORM="${PLATFORM:-}"                                  # e.g. linux/amd64 for multi-arch build hosts
BASE_IMAGE="${BASE_IMAGE:-}"                              # override the FROM line, e.g. langchain/langgraph-api:3.12-wolfi-fips

NAMESPACE="${NAMESPACE:-agent-server}"
RELEASE="${RELEASE:-agent-server}"
CHART="${CHART:-langchain/langgraph-cloud}"
CHART_VERSION="${CHART_VERSION:-0.3.4}"
VALUES_FILES="${VALUES_FILES:-$REPO_ROOT/sample/helm/values-dev.yaml}"   # space-separated
HELM_TIMEOUT="${HELM_TIMEOUT:-5m}"

if [ -n "$REGISTRY" ]; then
  IMAGE_REF="$REGISTRY/$IMAGE_REPO:$IMAGE_TAG"
  HELM_IMAGE_REPO="$REGISTRY/$IMAGE_REPO"
else
  IMAGE_REF="$IMAGE_REPO:$IMAGE_TAG"
  HELM_IMAGE_REPO="$IMAGE_REPO"
fi

log() { printf '\n==> %s\n' "$*"; }
